# Generated by Django 5.2.17 on 2026-09-14 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('organization', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place'), ('finalist', 'Finalist')], default='finalist', max_length=10)),
                ('photo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
